api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.index, name='index'),
    path('pony/', views.pony, name='pony'),
    path('pony_lookup', views.pony_lookup, name='pony_lookup'),
    path('pony/<str:pony_id>', views.fetch_pony, name='fetch_pony'),
]

gen/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

api/models.py
# from django.db import models

# Create your models here.

api/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# Create your views here.
def index(request):
    context = {}
    return render(request, 'api/index.html', context)


def pony(request):
    context = {}
    return render(request, 'api/pony.html', context)


def pony_lookup(request):
    pony_id: str = request.POST['pony']
    if int(pony_id) <= 0 or pony_id is None:
        return HttpResponse('The pony id must be a number greater then 0.', status=500)
    return HttpResponseRedirect(reverse('api:fetch_pony', args=(pony_id, )))


def fetch_pony(request, pony_id):
    if int(pony_id) <= 0 or pony_id is None:
        return HttpResponse('The pony id must be a number greater then 0.', status=500)
    return HttpResponse("You're looking at pony %s." % pony_id)

gen/views.py
from django.http import HttpResponse


# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the main index. Visit <a href=\"/api\">the api</a>")

api/templates/api/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gen API</title>
</head>
<body>
<h1>Available endpoints</h1>
<ul>
    <li><a href="{% url 'api:pony' %}">/pony</a></li>
</ul>
</body>
</html>

api/templates/api/pony.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pony Lookup</title>
</head>
<body>
<h1>Pony lookup</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'api:pony_lookup' %}" method="post">
{% csrf_token %}
<input type="text" name="pony" id="pony" value="">
    <label for="pony">Enter a pony id</label><br>
<input type="submit" value="Lookup">
</form>
</body>
</html>